In [55]:
import numpy as np

In [56]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

matrix

In [57]:
b= np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

shape

In [58]:
print(a.shape,b.shape)

(4,) (2, 2)


In [59]:
# reshape
c=a.reshape((4,1))
c


array([[1],
       [2],
       [3],
       [4]])

In [60]:
c.shape

(4, 1)

In [61]:
a.shape

(4,)

In [62]:
# ضرب اعداد باید با تعداد المان های آن برابر باشد گثلا آن 4المان دارد 
d=a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [63]:
# زمانی که نمیدانید
d=a.reshape((2,-1,2))
d.shape

(2, 1, 2)

In [64]:
# concatination
a=np.array([1,2,3])
b=np.array([3,4,5])
c=np.concatenate((a,b))
c

array([1, 2, 3, 3, 4, 5])

In [17]:
a=np.array([1,2,3])
b=np.array([3,4,5])
c=a+b
c

array([4, 6, 8])

In [18]:
a=np.array([1,2,3])
b=np.array([3,4,5])
c=a*b
c

array([ 3,  8, 15])

In [20]:
# broadcasting
c= np.array([10])
d=a+c
d

array([11, 12, 13])

In [21]:
e=b+5
e

array([ 8,  9, 10])

In [22]:
a=np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [23]:
# slice
b=a[2:7]
b

array([3, 4, 5, 6, 7])

In [24]:
b=a[2:7:2]
b

array([3, 5, 7])

In [25]:
c=a[a>3]
c

array([4, 5, 6, 7, 8])

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
# مجموع تمام المان های بردار
sum_a=np.sum(a)
sum_a

np.int64(36)

In [28]:
max_a=np.max(a)
max_a

np.int64(8)

In [29]:
min_a=np.min(a)
min_a

np.int64(1)

In [30]:
# sort data
a=np.array([4,2,9,6,7,3,5])
b=np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [31]:
# create random matix 
# (3,4)ابعاد
a=np.random.randint(0,10,(3,4))
a

array([[4, 3, 6, 7],
       [8, 5, 6, 3],
       [0, 6, 9, 2]], dtype=int32)

In [36]:
# vstack عمودی

# first array in first row and other in the second row
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
c


array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
c.shape

(3, 3)

In [37]:
# hstack list(tuple)افقی
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [38]:
# normalize:میانگین به سمت صفر و انحراف معیار به سمت 1 برود
#   1.mean2.std(انحراف معیار)3.norm_a= (a-mean_a)/std_a4.np.mean(norm_a)5.np.std(norm_a)


a

array([1, 2, 3])

In [39]:
mean_a=np.mean(a)
mean_a

np.float64(2.0)

In [40]:
std_a=np.std(a)
std_a

np.float64(0.816496580927726)

In [41]:
norm_a= (a-mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [42]:
np.mean(norm_a)

np.float64(0.0)

In [43]:
np.std(norm_a)

np.float64(0.9999999999999999)